---
# tasks file for ansible_galaxy_role_ubuntu-ntp-client

- name: "Set NTP Server to Ubuntu | change timesyncd.conf"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  shell:
    cmd: |
      cat "{{ timesyncd.file.path }}" | grep "#NTP=" >/dev/null
      if [ $? -eq 0 ]; then
        echo "already changed."
      else
        sed -i -e "s/#NTP=/NTP={{ ntp.server }}/g" "{{ timesyncd.file.path }}"
      fi
